test:
  adapter: postgresql
  encoding: unicode
  database: hiking_project_api
  pool: 5
  username: hiking_project_api
  password: horsefly32

development:
  adapter: postgresql
  encoding: unicode
  database: hiking_project_api
  pool: 5
  username: hiking_project_api
  password: horsefly32

production:
  adapter: postgresql
  encoding: unicode
  database: hiking_project_api
  host: localhost
  pool: 5
  username: hiking_project_api
  password: wcpStBFgS
